### ISSUE TITLE
pytorch_model-00001-of-00004.bin本地能用zip文件打开，执行generate.py报：RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by lizhao-8202** [FreedomIntelligence/GrammarGPT#8]
**python 3.10.12
transformers 4.28.0
本地LANG环境变量：zh_CN.UTF-8**

从https://huggingface.co/FreedomIntelligence/GrammarGPT/tree/main下载了最新模型文件放到了对应目录，运行python generate.py报错如下：

Loading checkpoint shards:   0%|                                                                                                                         | 0/4 [00:00<?, ?it/s]^^^^^^checkfile:savedmodel/pytorch_model-00001-of-00004.bin
Loading checkpoint shards:   0%|                                                                                                                         | 0/4 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/opt/python3.10/python3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 443, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "/opt/python3.10/python3/lib/python3.10/site-packages/torch/serialization.py", line 1004, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/opt/python3.10/python3/lib/python3.10/site-packages/torch/serialization.py", line 456, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
**RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python3.10/python3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 447, in load_state_dict
    if f.read(7) == "version":
  File "/opt/python3.10/python3/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 128: invalid start byte**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/AI/GrammarGPT/GrammarGPT-main/generate.py", line 188, in <module>
    main()
  File "/data/AI/GrammarGPT/GrammarGPT-main/generate.py", line 46, in main
    model = AutoModelForCausalLM.from_pretrained(
  File "/opt/python3.10/python3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/python3.10/python3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2796, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/opt/python3.10/python3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3110, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "/opt/python3.10/python3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 459, in load_state_dict
    raise OSError(
**OSError: Unable to load weights from pytorch checkpoint file for 'savedmodel/pytorch_model-00001-of-00004.bin' at 'savedmodel/pytorch_model-00001-of-00004.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.**

**试过删除~/.chche目录。结果一样
pytorch_model-00001-of-00004.bin 用本地解压缩软件可以打开**

**Comment by lizhao-8202** [comment]
**将本地语言编码设置为en_US.ISO-8859-1报错如下**

###########base_modelsavedmodel
Loading checkpoint shards:   0%|                                                                                                                         | 0/4 [00:00<?, ?it/s]^^^^^^checkfile:savedmodel/pytorch_model-00001-of-00004.bin
Loading checkpoint shards:   0%|                                                                                                                         | 0/4 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/opt/python3.10/python3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 443, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "/opt/python3.10/python3/lib/python3.10/site-packages/torch/serialization.py", line 1004, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/opt/python3.10/python3/lib/python3.10/site-packages/torch/serialization.py", line 456, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
**RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory**

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python3.10/python3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 454, in load_state_dict
    raise ValueError(
**ValueError: Unable to locate the file savedmodel/pytorch_model-00001-of-00004.bin which is necessary to load this pretrained model. Make sure you have saved the model properly.**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/AI/GrammarGPT/GrammarGPT-main/generate.py", line 188, in <module>
    main()
  File "/data/AI/GrammarGPT/GrammarGPT-main/generate.py", line 46, in main
    model = AutoModelForCausalLM.from_pretrained(
  File "/opt/python3.10/python3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/python3.10/python3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2796, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/opt/python3.10/python3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3110, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "/opt/python3.10/python3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 459, in load_state_dict
    raise OSError(
**OSError: Unable to load weights from pytorch checkpoint file for 'savedmodel/pytorch_model-00001-of-00004.bin' at 'savedmodel/pytorch_model-00001-of-00004.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.**

**Comment by lizhao-8202** [comment]
最后一处报错为什么提到了TF 2.0 。我们从https://huggingface.co/FreedomIntelligence/GrammarGPT/tree/main(https://huggingface.co/FreedomIntelligence/GrammarGPT/tree/main下载的模型没用到TF吧

**Comment by fjiangAI** [comment]
> 最后一处报错为什么提到了TF 2.0 。我们从[https://huggingface.co/FreedomIntelligence/GrammarGPT/tree/main(https://huggingface.co/FreedomIntelligence/GrammarGPT/tree/main下载的模型没用到TF吧](https://huggingface.co/FreedomIntelligence/GrammarGPT/tree/main(https://huggingface.co/FreedomIntelligence/GrammarGPT/tree/main%E4%B8%8B%E8%BD%BD%E7%9A%84%E6%A8%A1%E5%9E%8B%E6%B2%A1%E7%94%A8%E5%88%B0TF%E5%90%A7)

这个主要看你的系统环境，正常是用的ubuntu系统，如果使用windows或者mac的话，有可能会有编码问题。另外后面提到的TF它的意思是如果读不了，可能是因为你文件本身就不对，所以才说有可能是TF的模型。

因此，最重要的是需要确认系统是什么系统，然后再根据情况搜索一下如何解决。

**Comment by lizhao-8202** [comment]
> > 最后一处报错为什么提到了TF 2.0 。我们从[https://huggingface.co/FreedomIntelligence/GrammarGPT/tree/main(https://huggingface.co/FreedomIntelligence/GrammarGPT/tree/main下载的模型没用到TF吧](https://huggingface.co/FreedomIntelligence/GrammarGPT/tree/main(https://huggingface.co/FreedomIntelligence/GrammarGPT/tree/main%E4%B8%8B%E8%BD%BD%E7%9A%84%E6%A8%A1%E5%9E%8B%E6%B2%A1%E7%94%A8%E5%88%B0TF%E5%90%A7)
> 
> 这个主要看你的系统环境，正常是用的ubuntu系统，如果使用windows或者mac的话，有可能会有编码问题。另外后面提到的TF它的意思是如果读不了，可能是因为你文件本身就不对，所以才说有可能是TF的模型。
> 
> 因此，最重要的是需要确认系统是什么系统，然后再根据情况搜索一下如何解决。

我这边操作系统用的是x86架构的**centos 7.9**。然后我的torch版本是**2.3.0.**
想问下我们的模型在训练时用的torch版本是多少呢。
我试了下单独对模型文件用torch.load(文件名)去加载一样报错（模型文件一共是4个，从01-04都试了下，都报错）。

**Comment by lizhao-8202** [comment]
> > > 最后一处报错为什么提到了TF 2.0 。我们从[https://huggingface.co/FreedomIntelligence/GrammarGPT/tree/main(https://huggingface.co/FreedomIntelligence/GrammarGPT/tree/main下载的模型没用到TF吧](https://huggingface.co/FreedomIntelligence/GrammarGPT/tree/main(https://huggingface.co/FreedomIntelligence/GrammarGPT/tree/main%E4%B8%8B%E8%BD%BD%E7%9A%84%E6%A8%A1%E5%9E%8B%E6%B2%A1%E7%94%A8%E5%88%B0TF%E5%90%A7)
> > 
> > 
> > 这个主要看你的系统环境，正常是用的ubuntu系统，如果使用windows或者mac的话，有可能会有编码问题。另外后面提到的TF它的意思是如果读不了，可能是因为你文件本身就不对，所以才说有可能是TF的模型。
> > 因此，最重要的是需要确认系统是什么系统，然后再根据情况搜索一下如何解决。
> 
> 我这边操作系统用的是x86架构的**centos 7.9**。然后我的torch版本是**2.3.0.** 想问下我们的模型在训练时用的torch版本是多少呢。 我试了下单独对模型文件用torch.load(文件名)去加载一样报错（模型文件一共是4个，从01-04都试了下，都报错）。

让他们重新帮下载了个模型，现在没问题了。非常感谢啊

**Comment by lizhao-8202** [comment]
完结
